export const images = [
  { name: "Black Mountain.jpg", qty: 0 },
  { name: "Black Velvet.jpg", qty: 0 },
  { name: "Bonanza Trail.jpg", qty: 0 },
  { name: "Bridge 360.jpg", qty: 10 },
  { name: "Bridge Mountain.jpg", qty: 0 },
  { name: "Bridge Point.jpg", qty: 0 },
  { name: "Bridge Vista.jpg", qty: 0 },
  { name: "Brownstone.jpg", qty: 40 },
  { name: "Burlap Buttress.jpg", qty: 0 },
  { name: "Calico Shark Fin.jpg", qty: 30 },
  { name: "Charleston.jpg", qty: 50 },
  { name: "Crabby.jpg", qty: 0 },
  { name: "Evas Tower.jpg", qty: 40 },
  { name: "First Creek.jpg", qty: 0 },
  { name: "Goodman.jpg", qty: 30 },
  { name: "Griffith.jpg", qty: 100 },
  { name: "Gunsight.jpg", qty: 30 },
  { name: "Haslv Level Chip - CARD SHARK.jpg", qty: 0 },
  { name: "Haslv Level Chip - GAMBLER.jpg", qty: 0 },
  { name: "Haslv Level Chip - HIGH ROLLER.jpg", qty: 0 },
  { name: "Haslv Level Chip - LOW ROLLER.jpg", qty: 0 },
  { name: "Haslv Level Chip - SPINNER.jpg", qty: 0 },
  { name: "Haslv Level Chip - WHALE.jpg", qty: 0 },
  { name: "Haslv Logo.jpg", qty: 0 },
  { name: "Holiday Peak.jpg", qty: 30 },
  { name: "Ice Box.jpg", qty: 30 },
  { name: "Indecision.jpg", qty: 0 },
  { name: "Ive Been Lost Here.jpg", qty: 0 },
  { name: "Juniper Peak.jpg", qty: 30 },
  { name: "Kraft - No Route.jpg", qty: 30 },
  { name: "Lee Peak.jpg", qty: 0 },
  { name: "Lost Creek Graffiti Traverse.jpg", qty: 0 },
  { name: "Macks Peak.jpg", qty: 0 },
  { name: "Magic Mountain.jpg", qty: 100 },
  { name: "McFarland.jpg", qty: 0 },
  { name: "Mescalito.jpg", qty: 30 },
  { name: "Mummy Head to Toe.jpg", qty: 20 },
  { name: "Mummy Mountain.jpg", qty: 30 },
  { name: "Mummys Chin.jpg", qty: 20 },
  { name: "Mummys Forehead.jpg", qty: 20 },
  { name: "Mummys Head Loop.jpg", qty: 10 },
  { name: "Mummys Nose.jpg", qty: 40 },
  { name: "Mummys Toe.jpg", qty: 40 },
  { name: "North Macks Peak.jpg", qty: 0 },
  { name: "North Peak.jpg", qty: 0 },
  { name: "Oak Creek Overlook.jpg", qty: 0 },
  { name: "Oak Peak.jpg", qty: 0 },
  { name: "Pine Creek.jpg", qty: 0 },
  { name: "Rainbow.jpg", qty: 0 },
  { name: "Sisters.jpg", qty: 40 },
  { name: "Terrace Peak.jpg", qty: 0 },
  { name: "Turtle Peak Jr Double Slot.jpg", qty: 100 },
  { name: "White Pinnacle.jpg", qty: 50 },
  { name: "White Rock Hills Peak.jpg", qty: 40 },
  { name: "Wilson.jpg", qty: 30 },
];

export const total = images.reduce((a, i) => a + i.qty, 0);
